[package]
name = "unicorn-p2p-rng"
version = "0.1.0"
authors = ["Eugene P. <eupn@protonmail.com>"]

[dependencies]
actix = "0.7.4"
vdf = { git="https://github.com/eupn/vdf-rs.git" }
rug = "1.2.1"
rand = "0.3"
