[package]
name = "unicorn-p2p-rng"
version = "0.2.0"
authors = ["Eugene P. <eupn@protonmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
vdf = "0.1.0"
rand = "0.3"
hex = "0.3.2"
sha2 = "0.8.0"
digest = "0.8.0"
